feat: obfuscation
tensorplex-labs/dojo-archived pull request #71
Opened 2024-11-13 09:17 UTC by karootplx

2024-11-14 07:54 UTC, codebender37 commented on commons/obfuscation/obfuscation_utils.py
> +import minify_html
is it new package? if so, can you add it in pyproject too?

2024-11-16 16:30 UTC, jarvis8x7b requested changes

2024-11-16 16:30 UTC, jarvis8x7b commented on commons/obfuscation/obfuscation_utils.py
> +        return Obfuscator.generate_random_string(length)
can remove subclassing here due zero additional logic in wrapper func

2024-11-16 16:30 UTC, jarvis8x7b commented on neurons/validator.py
> +                random.shuffle(shuffled_completions)
imo it is better to use sample here because keeping track of side effects would probably lead to bugs down the line

2025-03-03 08:03 UTC, closed without merging