refactor: update schema and migration script
tensorplex-labs/dojo-archived pull request #77
Opened 2024-11-27 15:12 UTC by karootplx

2024-12-23 08:09 UTC, jarvis8x7b requested changes

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/human_feedback/dojo.py
>                      return None
can remove this block as it's caught by the later return statement

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/human_feedback/dojo.py
> +        for completion in data.completion_responses:
check for completion responses None or add type ignore for type checking to pass

2024-12-23 08:09 UTC, jarvis8x7b commented on dojo/protocol.py
> +    DIALOGUE = "DIALOGUE"
can clear this TODO here, fixes type issues in `commons/human_feedback/dojo.py` with DialogueItem

2024-12-23 08:09 UTC, jarvis8x7b commented on dojo/protocol.py
>  )
thinking if we can shift all types to a separate file but not 100% sure if it's the best practice

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/human_feedback/dojo.py
> +        raise CreateTaskFailed(f"Failed to create task after {cls.MAX_RETRIES} retries")
can remove 2 possible exit paths, so it also aligns the 2 error messages for future debugging

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/logging/wandb.py
> +    return run
can remove the run var as is not being used

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/orm.py
> +        include_query = ValidatorTaskWhereInput(
should be `ValidatorTaskInclude`

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/orm.py
> +    ) -> None:
properly type hint to `int | None`

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/orm.py
> +                                }
can construct the `MinerResponseWhereInput` object

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/orm.py
> +    # async def get_task_by_request_id(request_id: str) -> DendriteQueryResponse | None:
nuke the function

2024-12-23 08:09 UTC, jarvis8x7b commented on commons/orm.py
> +                                    where={
can construct the `CriterionWhereInput`

2024-12-23 08:33 UTC, jarvis8x7b commented on schema.prisma
> +    GroundTruth     GroundTruth[]
use snake_case for consistency

2024-12-23 09:22 UTC, codebender37 commented on migration.py
> +                        "expire_at": old_request.expire_at,
I don't think we need `expire_at`

2024-12-23 09:32 UTC, jarvis8x7b commented on commons/orm.py
> +                "GroundTruth": True,
change to snake_case after refactoring prisma schema

2024-12-23 09:39 UTC, jarvis8x7b commented on commons/orm.py
> +                                    rank_id=completion.rank_id,
missing parameter on the `Scores` model

2024-12-23 09:41 UTC, jarvis8x7b commented on commons/orm.py
> +                                        "criterion_id_miner_response_id": {
haven't seen this syntax before, just checking if it's intentional?

2024-12-23 09:47 UTC, jarvis8x7b commented on commons/orm.py
>      async def create_or_update_validator_score(scores: torch.Tensor) -> None:
if using an instance method, must have `self` as the first parameter

2024-12-23 09:57 UTC, jarvis8x7b commented on neurons/validator.py
> +        sel_miner_uids = sorted(list(self._active_miner_uids))
should acquire the `self._uids_alock`

2024-12-23 10:00 UTC, jarvis8x7b commented on neurons/validator.py
> +    async def _generate_synthetic_request(self) -> tuple[TaskSynapseObject, str] | None:
hint should be `tuple[Task..., dict] | None`

2024-12-23 10:00 UTC, jarvis8x7b commented on neurons/validator.py
> +                return None
return 2 Nones, or None and empty dict so number of arguments are the same

2024-12-23 10:01 UTC, jarvis8x7b commented on dojo/protocol.py
> +class Scores(BaseModel):
add `rank_id` to resolve missing parameter

2024-12-23 10:09 UTC, jarvis8x7b commented on commons/orm.py
> +                data=Score_ModelUpdateInput(score=(json.dumps(scores_list))),
we generally use prisma Json in other places as well, why remove here

2024-12-23 10:10 UTC, daemontplx commented
think we can nuke the following files along with this refactoring since its not used:
- commons/api/*
- commons/dataset/leaderboard.py

2024-12-23 10:10 UTC, jarvis8x7b commented on commons/orm.py
> +                    score=(json.dumps(scores_list)),
we generally use prisma Json in other places as well, why remove here

2024-12-23 10:20 UTC, jarvis8x7b commented on commons/scoring.py
> +        miner_responses: List[TaskSynapseObject],
can remove the `cmp_ground_truth` function as we dont use it anymore

2024-12-23 10:20 UTC, jarvis8x7b commented on commons/scoring.py
> +        miner_responses: List[TaskSynapseObject],
can remove the `spm_ground_truth` function as we dont use it anymore

2024-12-23 10:20 UTC, jarvis8x7b commented on commons/scoring.py
> +    def _assign_scores(
i understand that `calculate_score` is the overall scoring function, but what's the difference between `_assign_scores` and `ground_truth_scoring` as you are performing ground_truth_scoring in this function as well, perhaps `def score_by_criteria` is more appropriate

2024-12-24 06:45 UTC, codebender37 commented on neurons/validator.py
> +                    ) = await self._generate_synthetic_request()
This might waste the API usage?? I feel like we could generate the task after we found active miner

2024-12-26 09:11 UTC, codebender37 commented on neurons/validator.py
> +                    response.axon.coldkey if response.axon else None
I think axon doesn't have field for `coldkey`

2024-12-26 10:18 UTC, codebender37 commented on commons/orm.py
> +    Json,
I have some issue with this `Json` but this works for me
`from database.prisma import Json`

2024-12-26 11:35 UTC, codebender37 commented on neurons/validator.py
> +                    response.axon.coldkey if response.axon else None
I guess that might be the causing this
`2024-12-26 18:03:29.133 |      ERROR       |       neurons.validator:send_request:937 |  - Error processing miner response: 'TerminalInfo' object has no attribute 'coldkey' -
`

2024-12-27 09:54 UTC, karootplx commented on neurons/validator.py
> +                    ) = await self._generate_synthetic_request()
done. will push shortly

2024-12-27 09:55 UTC, karootplx commented on neurons/validator.py
> +                    response.axon.coldkey if response.axon else None
done. will get coldkey via self.metagraph

2025-01-02 03:56 UTC, karootplx commented on commons/human_feedback/dojo.py
> +        for completion in data.completion_responses:
done

2025-01-02 04:01 UTC, karootplx commented on commons/logging/wandb.py
> +    return run
done

2025-01-02 04:02 UTC, karootplx commented on schema.prisma
> +    GroundTruth     GroundTruth[]
done

2025-01-02 04:03 UTC, karootplx commented on commons/orm.py
> +        include_query = ValidatorTaskWhereInput(
done

2025-01-02 04:04 UTC, karootplx commented on commons/orm.py
> +                "GroundTruth": True,
done

2025-01-02 04:04 UTC, karootplx commented on commons/orm.py
> +    ) -> None:
done

2025-01-02 04:05 UTC, karootplx commented on commons/orm.py
> +    # async def get_task_by_request_id(request_id: str) -> DendriteQueryResponse | None:
done

2025-01-02 04:10 UTC, karootplx commented on dojo/protocol.py
> +    DIALOGUE = "DIALOGUE"
done

2025-01-02 04:21 UTC, karootplx commented on neurons/validator.py
> +    async def _generate_synthetic_request(self) -> tuple[TaskSynapseObject, str] | None:
done

2025-01-02 04:22 UTC, karootplx commented on neurons/validator.py
> +                return None
done

2025-01-02 04:24 UTC, karootplx commented on neurons/validator.py
> +        sel_miner_uids = sorted(list(self._active_miner_uids))
done

2025-01-03 04:15 UTC, karootplx commented on commons/human_feedback/dojo.py
>                      return None
done

2025-01-03 04:18 UTC, karootplx commented on commons/orm.py
> +                                    rank_id=completion.rank_id,
done

2025-01-03 05:03 UTC, karootplx commented on commons/orm.py
> +                                        "criterion_id_miner_response_id": {
yup its because of this constraint 
![image](https://github.com/user-attachments/assets/64444a1a-b5eb-4d47-ad8f-8498c7481ef8)

2025-01-03 05:05 UTC, karootplx commented on commons/scoring.py
> +    def _assign_scores(
done

2025-01-03 05:05 UTC, karootplx commented on dojo/protocol.py
> +class Scores(BaseModel):
done

2025-01-03 05:06 UTC, karootplx commented on migration.py
> +                        "expire_at": old_request.expire_at,
done

2025-01-03 05:07 UTC, karootplx commented on commons/human_feedback/dojo.py
> +        raise CreateTaskFailed(f"Failed to create task after {cls.MAX_RETRIES} retries")
done

2025-01-03 05:08 UTC, karootplx commented on commons/orm.py
> +                                }
done

2025-01-03 05:08 UTC, karootplx commented on commons/orm.py
> +                                    where={
done

2025-01-03 05:10 UTC, karootplx commented on commons/orm.py
>      async def create_or_update_validator_score(scores: torch.Tensor) -> None:
removed this function altogether

2025-01-03 05:14 UTC, karootplx commented on commons/orm.py
> +                    score=(json.dumps(scores_list)),
done

2025-01-03 05:14 UTC, karootplx commented on commons/orm.py
> +    Json,
same here. fixed

2025-01-06 03:56 UTC, jarvis8x7b commented on schema.prisma
> +
let's add the metadata column, i feel it should be tagged to the validator task

2025-01-09 04:21 UTC, jarvis8x7b approved these changes
lgtm

2025-01-09 08:45 UTC, merged

2025-01-23 05:20 UTC, Tedbees commented
:tada: This PR is included in version 1.6.1 :tada:

The release is available on [GitHub release](https://github.com/tensorplex-labs/dojo/releases/tag/v1.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: