refactor: migrate score data from db to .pt file
tensorplex-labs/dojo-archived pull request #80
Opened 2024-12-02 07:54 UTC by codebender37

2024-12-03 07:32 UTC, jarvis8x7b requested changes

2024-12-03 07:32 UTC, jarvis8x7b commented on .env.miner.example
> +
can we shift this to the top? this section is meant for decentralized env vars

2024-12-03 07:32 UTC, jarvis8x7b commented on dojo/utils/uids.py
> +    print(f"Validator min stake {VALIDATOR_MIN_STAKE}")
use bt logging

2024-12-03 10:32 UTC, codebender37 commented on dojo/utils/uids.py
> +    print(f"Validator min stake {VALIDATOR_MIN_STAKE}")
oh, sorry forget to remove

2024-12-03 18:01 UTC, karootplx approved these changes
lgtm

2024-12-04 02:31 UTC, jarvis8x7b requested changes

2024-12-04 02:31 UTC, jarvis8x7b commented on .env.miner.example
> +# VALIDATOR_MIN_STAKE=1
set this to 20k so that if the miner forgets it's set properly

2024-12-04 02:36 UTC, jarvis8x7b commented on README.md
> +VALIDATOR_MIN_STAKE= # minimum stake required for validators default is 20000 TAO (use this to bypass the blacklist function in testnet)
can set to the default 20k value

2024-12-04 08:08 UTC, jarvis8x7b approved these changes

2024-12-04 10:39 UTC, merged