fix: hotfix for db connection issue
tensorplex-labs/dojo-archived pull request #95
Opened 2024-12-11 04:14 UTC by codebender37

- removed disconnect_db() in migrate_from_db

2024-12-11 04:23 UTC, karootplx approved these changes
lgtm

2024-12-11 04:47 UTC, jarvis8x7b requested changes

2024-12-11 04:47 UTC, jarvis8x7b commented on neurons/validator.py
>          if not migration_success:
add a log for the case migration_success = True

2024-12-11 13:04 UTC, jarvis8x7b approved these changes
lgtm

2024-12-11 13:05 UTC, merged

2024-12-12 15:47 UTC, Tedbees commented
:tada: This PR is included in version 1.5.1 :tada:

The release is available on [GitHub release](https://github.com/tensorplex-labs/dojo/releases/tag/v1.5.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: